
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-xcode"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/xcode-project"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "howett.net/plist"

[prune]
  go-tests = true
  unused-packages = true
